### PR TITLE
smooth wave for duration lower than 1 second

### PR DESCRIPTION
**Pull request by samkoesnadi**
The original code produces a sound that cracks if the duration is not a whole number. This is because the produced wave stops at a value that is not resting at 0. This code fixes that.

### CODE REVIEW

**Review by lneuhaus — APPROVED** [review]
Thanks! Can you merge this when you feel it’s finished or do I have to do it?

**Comment by samkoesnadi** [comment]
It is my pleasure. I think you can merge it, also because I do not have the write access to the repository.

@lneuhaus

**Comment by samuelmat19** [comment]
@lneuhaus

**Comment by samkoesnadi** [comment]
I just want to ping you, as a follow-up to this PR.

@lneuhaus

**Comment by lneuhaus** [comment]
tHANKS @samuelmat19

**Pull request merged**
